#!/usr/bin/env python3
"""Write docs/flavour-audit.md: how every variety's flavour notes stand against the evidence (run after tools/build.py).

    python tools/flavour_audit.py

Lists notes dropped (no support / contradicted), notes added, varieties nobody describes, single-source notes, and
1-5 sweet/acid scores that disagree with lab measurements or with what the sources say.
"""
import json, os
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CENTRE = {1: 10, 2: 30, 3: 50, 4: 70, 5: 90}          # a 1-5 score as the percentile it implies


def ordinal(n):
    return "%d%s" % (n, "th" if 10 <= n % 100 <= 20 else {1: "st", 2: "nd", 3: "rd"}.get(n % 10, "th"))


def main():
    data = json.load(open(os.path.join(ROOT, "assets", "data.json"), encoding="utf-8"))
    fl = json.load(open(os.path.join(ROOT, "assets", "flavour.json"), encoding="utf-8"))
    vs, det = data["varieties"], fl["varieties"]
    L = []
    lv = Counter()
    single = Counter()
    for v in vs:
        for tg in v["taste"]["tags"]:
            n = v["taste"].get("support", {}).get(tg, 0)
            lv["firm (3+)" if n >= 3 else "supported (2)" if n == 2 else "reported (1)" if n == 1 else "unsourced (0)"] += 1
            if n == 1:
                single[tg] += 1
    nsrc = Counter(min(v["taste"].get("n_sources", 0), 4) for v in vs)
    L.append("# Flavour audit\n")
    L.append("Generated by `tools/flavour_audit.py` from `assets/data.json` (built %s). Method: docs/decisions/0005.\n" % data["built"])
    L.append("## Summary\n")
    L.append("| | count |\n|---|---|")
    for k in ("firm (3+)", "supported (2)", "reported (1)", "unsourced (0)"):
        L.append("| tags %s | %d |" % (k, lv[k]))
    L.append("| varieties with 0 / 1 / 2 / 3 / 4+ independent sources | %s |" % " / ".join(str(nsrc[i]) for i in range(5)))
    L.append("| varieties with an entry in an old book | %d |" % sum(1 for v in vs if v["taste"].get("n_books")))
    L.append("| varieties with lab sugar/acid data | %d |" % sum(1 for v in vs if v["taste"].get("measured")))
    L.append("| notes dropped (no support) | %d |" % sum(len(d.get("unverified", [])) for d in det.values()))
    L.append("| notes dropped (contradicted) | %d |" % sum(len(d.get("contested", [])) for d in det.values()))
    L.append("| notes added (2+ sources) | %d |\n" % sum(len(d.get("added", [])) for d in det.values()))

    def section(title, rows, head):
        L.append("## %s\n" % title)
        if not rows:
            L.append("None.\n"); return
        L.append(head)
        L.append("|" + "---|" * (head.splitlines()[-1].count("|") - 1))
        L.extend(rows)
        L.append("")

    byid = {v["id"]: v for v in vs}
    rows = []
    for vid, d in sorted(det.items(), key=lambda x: byid[x[0]]["name"]):
        if d.get("unverified") or d.get("contested") or d.get("added"):
            con = ["%s (against: %s)" % (tg, ", ".join(d["contra"].get(tg, []))) for tg in d.get("contested", [])]
            rows.append("| [%s](https://otac0011.github.io/pomography/#/v/%s) | %s | %s | %s | %d |" % (
                byid[vid]["name"], vid, ", ".join(d.get("unverified", [])) or "", "; ".join(con),
                ", ".join(d.get("added", [])), byid[vid]["taste"].get("n_sources", 0)))
    section("Changes to flavour notes", rows, "| Variety | Dropped: no support | Dropped: contradicted | Added | Sources |")

    rows = []
    for v in vs:
        t = v["taste"]
        exp = {k: CENTRE.get(t.get(k)) for k in ("sweet", "acid")}
        m = t.get("measured") or {}
        for k, pk in (("sweet", "pct_ssc"), ("acid", "pct_ta")):
            if exp[k] is not None and m.get(pk) is not None and abs(exp[k] - m[pk]) >= 40:
                rows.append("| %s | %s | %d/5 | measured at the %s percentile (%s) |" % (
                    v["name"], k, t[k], ordinal(round(m[pk])), ("%s °Brix" % m["ssc"]) if k == "sweet" else ("%s g/L" % m["ta"])))
        p = t.get("panel") or {}
        for k in ("sweet", "acid"):
            if t.get(k) and p.get(k) and abs((p[k] + 1) / 2 - t[k]) >= 2:      # 1-9 -> 1-5
                rows.append("| %s | %s | %d/5 | National Fruit Collection taster: %d/9 |" % (v["name"], k, t[k], p[k]))
        d = det.get(v["id"]) or {}
        for k in ("sweet", "acid"):
            said = [b.get(k) for b in d.get("books", []) if b.get(k)]
            if t.get(k) and said and abs(sorted(said)[len(said) // 2] - t[k]) >= 2:
                rows.append("| %s | %s | %d/5 | old books say %s/5 |" % (v["name"], k, t[k], ", ".join(map(str, said))))
    caveat = ("Read with care: °Brix measures sugar, not perceived sweetness (a very acid apple such as Bramley tastes sharp "
              "with average sugar), lab fruit is usually picked at commercial harvest rather than eating ripeness, and "
              "percentiles are within each dataset. These rows are prompts to re-check the 1-5 scores, not automatic "
              "corrections.\n\n")
    section("Sweet / sharp scores that disagree with the evidence", rows, caveat + "| Variety | Score | Ours | Evidence |")

    none = sorted(v["name"] for v in vs if not v["taste"].get("n_sources"))
    L.append("## Varieties with no independent source yet (%d)\n" % len(none))
    L.append(", ".join(none) + "\n" if none else "None.\n")

    L.append("## Notes resting on a single source\n")
    L.append(", ".join("%s (%d)" % kv for kv in single.most_common()) + "\n")

    rows = ["| %s | %s |" % (byid[vid]["name"], d["notes"].replace("|", "/").replace("\n", " "))
            for vid, d in sorted(det.items(), key=lambda x: byid[x[0]]["name"]) if d.get("notes")]
    section("Researchers' notes (disagreements, homonyms)", rows, "| Variety | Note |")
    os.makedirs(os.path.join(ROOT, "docs"), exist_ok=True)
    open(os.path.join(ROOT, "docs", "flavour-audit.md"), "w", encoding="utf-8").write("\n".join(L))
    print("wrote docs/flavour-audit.md:", dict(lv))


if __name__ == "__main__":
    main()
