#!/usr/bin/env python3
"""Which heirloom apples are missing? Reads research/coverage-gaps.json (run tools/coverage_gaps.py first) and writes
research/heirloom-gaps.md and .json.

    python tools/heirloom_gaps.py

A missing name counts here when it is on at least one of the heirloom lists (Temperate Orchard Conservancy, Pomiferous,
EURISCO). Each is then looked up in the old books in library/text: a name printed in a pomology from 1831-1920 is an
apple documented before 1925, i.e. an heirloom by any definition. A book hit is a line of the OCR text that opens with
the name (two or more words), or with the name in capitals for one-word names - the way these books head their entries.
Names made only of common words are left out of that test, and sports/strains (SKIP, "Spur", "... Delicious") are dropped.
"""
import json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
from coverage_gaps import HEIRLOOM, SKIP  # noqa: E402
from import_chemistry import norm  # noqa: E402

COMMON = set("""red green yellow white black golden gold sweet sour winter summer autumn fall early late june july august
september october queen king beauty pippin russet seedling apple crab pearmain reinette rambo greening blush striped
favorite favourite best late big long large small sweeting""".split())


def books():
    """Per book, the set of 1-5 word openings of each line: entries in a pomology start a line with the apple's name.
    Single-word names only count when printed in capitals ("HARVEY."), the heading style of these books."""
    out = {}
    for f in sorted(os.listdir(os.path.join(ROOT, "library", "text"))):
        if not f.endswith(".txt"):
            continue
        heads, caps = set(), set()
        for ln in open(os.path.join(ROOT, "library", "text", f), encoding="utf-8", errors="replace"):
            words = re.sub(r"[^a-z0-9]+", " ", norm(ln)).split()[:5]
            for n in range(2, len(words) + 1):
                heads.add(" ".join(words[:n]))
            m = re.match(r"\s*([A-Z][A-Z'’-]{4,})[.,\s]", ln)
            if m:
                caps.add(norm(m.group(1)))
        out[f[:-4]] = (heads, caps)
    return out


def searchable(name):
    words = re.sub(r"[^a-z0-9]+", " ", norm(name)).split()
    if not words or all(w in COMMON for w in words):
        return None
    return " ".join(words)


def in_book(key, book):
    heads, caps = book
    return key in caps if " " not in key else key in heads


SPORT = re.compile(r"\b(spur|double red|sport|strain|clone)\b|\b(delicious|mcintosh|gala|fuji|jonagold|braeburn|elstar|"
                   r"granny smith|cripps pink)$", re.I)


def main():
    gaps = json.load(open(os.path.join(ROOT, "research", "coverage-gaps.json"), encoding="utf-8"))
    texts = books()
    rows = []
    for m in gaps["missing"]:
        h = [s for s in m["sources"] if s in HEIRLOOM]
        if not h:
            continue
        if m["name"] in SKIP or SPORT.search(m["name"]):
            continue                              # sports and strains of apples we have are not separate heirlooms
        keys = [k for k in (searchable(n) for n in [m["name"]] + m["aka"]) if k]
        hits = sorted({b for b, t in texts.items() for k in keys if in_book(k, t)})
        rows.append(dict(m, heirloom=h, books=hits, other=[s for s in m["sources"] if s not in HEIRLOOM]))
    # strongest first: how many lists, then old-book evidence
    rows.sort(key=lambda r: (-(len(r["heirloom"]) + len(r["other"]) + min(2, len(r["books"]))), r["name"].lower()))

    def tier(r):
        n = len(r["heirloom"]) + len(r["other"])
        if n >= 3 and r["books"]:
            return "A"
        if n >= 3 or (n >= 2 and r["books"]):
            return "B"
        return "C"
    for r in rows:
        r["tier"] = tier(r)
    json.dump(rows, open(os.path.join(ROOT, "research", "heirloom-gaps.json"), "w", encoding="utf-8"), indent=1, ensure_ascii=False)
    count = {t: sum(1 for r in rows if r["tier"] == t) for t in "ABC"}
    L = ["# Heirloom gaps\n", "Generated by `tools/heirloom_gaps.py` from `research/coverage-gaps.json`. Every name here is "
         "on at least one heirloom list (Temperate Orchard Conservancy = TOC, Pomiferous, EURISCO) and not in the atlas.\n",
         "* **A** (%d): on 3+ lists and printed in an old pomology (1831-1920)." % count["A"],
         "* **B** (%d): on 3+ lists, or on 2 and in an old book." % count["B"],
         "* **C** (%d): the rest (mostly on one or two lists only).\n" % count["C"]]
    for t in "AB":
        L.append("\n## Tier %s\n" % t)
        L.append("| Apple | lists | old books |")
        L.append("|---|---|---|")
        for r in rows:
            if r["tier"] == t:
                L.append("| %s | %s | %s |" % (r["name"], ", ".join(r["heirloom"] + r["other"]), ", ".join(r["books"]) or "-"))
    open(os.path.join(ROOT, "research", "heirloom-gaps.md"), "w", encoding="utf-8").write("\n".join(L) + "\n")
    print("heirloom-list names missing from the atlas:", len(rows), count)


if __name__ == "__main__":
    main()
